# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  host: localhost
  username: root
  database: ticket
  password:

test:
  adapter: mysql2
  host: localhost
  username: root
  database: ticket_test
  password:

production:
  <<: *default
  database: db/production.sqlite3
